[*]
wallpaper_mode=color
wallpaper_common=1
wallpaper=/usr/share/rpd-wallpaper/clouds.jpg
desktop_bg=#3D3D3D
desktop_fg=#E8E8E8
desktop_shadow=#3D3846
desktop_font=Terminus Medium 9
show_wm_menu=0
sort=mtime;ascending;
show_documents=0
show_trash=1
show_mounts=1

[trash:///]
x=244
y=244

